# tarots_plugin - 配置文件
# 提供了抽塔罗牌占卜功能，具有模拟人类的调用方式和独特自定义风格的解牌回复。牌面为B站幻星集
# 配置版本: 2.1.1

# 插件基本配置
[plugin]

# 配置文件版本
config_version = "2.1.1"

# 是否启用插件
enabled = true


# 组件启用控制
[components]

# 启用塔罗牌占卜功能
enable_tarots = true

# 启用塔罗牌管理命令
enable_tarots_command = true


# 代理设置
[proxy]

# 是否启用代理
enable_proxy = false

# 代理服务器地址
proxy_url = ""


# 牌组配置
[cards]

# 当前使用牌组
using_cards = "bilibili"

# 可用牌组列表
use_cards = ['bilibili']


# 功能调整
[adjustment]

# 启用原始文本显示
enable_original_text = false


# 权限管理
[permissions]

# 管理员用户ID列表
admin_users = ["2785185004"]


